// swift-tools-version: 5.9
import PackageDescription

let package = Package(
    name: "FactoryGitOK",
    defaultLocalization: "en",
    platforms: [.macOS(.v14)],
    products: [
        .library(name: "FactoryGitOK", targets: ["FactoryGitOK"]),
    ],
    dependencies: [
        .package(path: "../KernelCore"),
        .package(path: "../KitLocalization"),
        .package(url: "https://github.com/CofficLab/LumiUI.git", branch: "main"),
        .package(path: "../PluginCommand"),
        .package(path: "../PluginCommitList"),
        .package(path: "../PluginGitDiff"),
        .package(path: "../PluginLogoCoffic"),
        .package(path: "../PluginLogoManager"),
        .package(path: "../PluginOpenAntigravity"),
        .package(path: "../PluginOpenCursor"),
        .package(path: "../PluginOpenFinder"),
        .package(path: "../PluginOpenGitHubDesktop"),
        .package(path: "../PluginOpenKiro"),
        .package(path: "../PluginOpenLumi"),
        .package(path: "../PluginOpenRemote"),
        .package(path: "../PluginOpenTerminal"),
        .package(path: "../PluginOpenTrae"),
        .package(path: "../PluginOpenVSCode"),
        .package(path: "../PluginOpenXcode"),
        .package(path: "../PluginPluginManager"),
        .package(path: "../PluginProjects"),
        .package(path: "../PluginSettingGeneral"),
        .package(path: "../PluginSettingView"),
        .package(path: "../PluginSettingsButton"),
        .package(path: "../PluginSidebar"),
        .package(path: "../PluginStatusBar"),
        .package(path: "../PluginStorage"),
        .package(path: "../PluginThemePack"),
        .package(path: "../ProviderCommand"),
        .package(path: "../KitGit"),
        .package(path: "../ProviderCommit"),
        .package(path: "../PluginCommitDetail"),
        .package(path: "../PluginCommitToast"),
        .package(path: "../PluginCommitStatusBar"),
        .package(path: "../ProviderContentView"),
        .package(path: "../ProviderDocsView"),
        .package(path: "../ProviderLogo"),
        .package(path: "../ProviderPluginControl"),
        .package(path: "../ProviderPluginManaging"),
        .package(path: "../ProviderRailView"),
        .package(path: "../ProviderRootView"),
        .package(path: "../ProviderSettingView"),
        .package(path: "../ProviderProjects"),
        .package(path: "../ProviderSidebar"),
        .package(path: "../ProviderStorage"),
        .package(path: "../ProviderStatusBar"),
        .package(path: "../ProviderTheme"),
        .package(path: "../ProviderToast"),
        .package(path: "../PluginToast"),
        .package(path: "../ProviderToolbar"),
    ],
    targets: [
        .target(
            name: "FactoryGitOK",
            dependencies: [
                .product(name: "KernelCore", package: "KernelCore"),
                .product(name: "KitLocalization", package: "KitLocalization"),
                .product(name: "LumiUI", package: "LumiUI"),
                .product(name: "ProviderContentView", package: "ProviderContentView"),
                .product(name: "ProviderDocsView", package: "ProviderDocsView"),
                .product(name: "ProviderRootView", package: "ProviderRootView"),
                .product(name: "ProviderSettingView", package: "ProviderSettingView"),
                .product(name: "ProviderProjects", package: "ProviderProjects"),
                .product(name: "ProviderSidebar", package: "ProviderSidebar"),
                .product(name: "ProviderStorage", package: "ProviderStorage"),
                .product(name: "ProviderStatusBar", package: "ProviderStatusBar"),
                .product(name: "ProviderTheme", package: "ProviderTheme"),
                .product(name: "ProviderToast", package: "ProviderToast"),
                .product(name: "PluginToast", package: "PluginToast"),
                .product(name: "ProviderToolbar", package: "ProviderToolbar"),
                .product(name: "PluginCommand", package: "PluginCommand"),
                .product(name: "PluginCommitList", package: "PluginCommitList"),
                .product(name: "PluginGitDiff", package: "PluginGitDiff"),
                .product(name: "PluginLogoCoffic", package: "PluginLogoCoffic"),
                .product(name: "PluginLogoManager", package: "PluginLogoManager"),
                .product(name: "PluginOpenAntigravity", package: "PluginOpenAntigravity"),
                .product(name: "PluginOpenCursor", package: "PluginOpenCursor"),
                .product(name: "PluginOpenFinder", package: "PluginOpenFinder"),
                .product(name: "PluginOpenGitHubDesktop", package: "PluginOpenGitHubDesktop"),
                .product(name: "PluginOpenKiro", package: "PluginOpenKiro"),
                .product(name: "PluginOpenLumi", package: "PluginOpenLumi"),
                .product(name: "PluginOpenRemote", package: "PluginOpenRemote"),
                .product(name: "PluginOpenTerminal", package: "PluginOpenTerminal"),
                .product(name: "PluginOpenTrae", package: "PluginOpenTrae"),
                .product(name: "PluginOpenVSCode", package: "PluginOpenVSCode"),
                .product(name: "PluginOpenXcode", package: "PluginOpenXcode"),
                .product(name: "PluginPluginManager", package: "PluginPluginManager"),
                .product(name: "PluginProjects", package: "PluginProjects"),
                .product(name: "PluginSettingGeneral", package: "PluginSettingGeneral"),
                .product(name: "PluginSettingView", package: "PluginSettingView"),
                .product(name: "PluginSettingsButton", package: "PluginSettingsButton"),
                .product(name: "PluginSidebar", package: "PluginSidebar"),
                .product(name: "PluginStatusBar", package: "PluginStatusBar"),
                .product(name: "PluginStorage", package: "PluginStorage"),
                .product(name: "PluginThemePack", package: "PluginThemePack"),
                .product(name: "ProviderCommand", package: "ProviderCommand"),
                .product(name: "KitGit", package: "KitGit"),
                .product(name: "ProviderCommit", package: "ProviderCommit"),
                .product(name: "PluginCommitDetail", package: "PluginCommitDetail"),
                .product(name: "PluginCommitToast", package: "PluginCommitToast"),
                .product(name: "PluginCommitStatusBar", package: "PluginCommitStatusBar"),
                .product(name: "ProviderLogo", package: "ProviderLogo"),
                .product(name: "ProviderPluginControl", package: "ProviderPluginControl"),
                .product(name: "ProviderPluginManaging", package: "ProviderPluginManaging"),
                .product(name: "ProviderRailView", package: "ProviderRailView"),
            ],
            path: "Sources/FactoryGitOK"
        ),
        .testTarget(
            name: "FactoryGitOKTests",
            dependencies: [
                "FactoryGitOK",
                .product(name: "KitGit", package: "KitGit"),
                .product(name: "ProviderCommit", package: "ProviderCommit"),
                .product(name: "ProviderToast", package: "ProviderToast"),
                .product(name: "PluginToast", package: "PluginToast"),
                .product(name: "PluginCommitToast", package: "PluginCommitToast"),
                .product(name: "PluginCommitStatusBar", package: "PluginCommitStatusBar"),
            ],
            path: "Tests/FactoryGitOKTests"
        ),
    ]
)
