// swift-tools-version: 6.0
import PackageDescription

let package = Package(
    name: "FactoryGitOK",
    defaultLocalization: "en",
    platforms: [.macOS(.v14)],
    products: [
        .library(name: "FactoryGitOK", targets: ["FactoryGitOK"]),
    ],
    dependencies: [
        .package(url: "https://github.com/CofficLab/LumiThemePack.git", from: "1.0.4"),
        .package(url: "https://github.com/CofficLab/LumiKernel.git", branch: "main"),
        .package(url: "https://github.com/CofficLab/LumiLocalization.git", from: "1.0.0"),
        .package(url: "https://github.com/CofficLab/LumiUI.git", from: "1.7.0"),
        .package(path: "../PluginActivityStatus"),
        .package(path: "../PluginCommand"),
        .package(path: "../PluginCloneRepository"),
        .package(path: "../PluginCommitDetail"),
        .package(path: "../PluginActivityHeatmap"),
        .package(path: "../PluginProjectLanguages"),
        .package(path: "../PluginCommitForm"),
        .package(path: "../PluginCommitList"),
        .package(path: "../PluginGitDiff"),
        .package(path: "../PluginGitBranchStatus"),
        .package(path: "../PluginGitUnpushedStatus"),
        .package(path: "../PluginGitUserSettings"),
        .package(path: "../PluginGitNetworkSettings"),
        .package(path: "../PluginGitRepositorySettings"),
        .package(path: "../PluginGitCommitStyleSettings"),
        .package(path: "../PluginGitStash"),
        .package(path: "../PluginGitConflictResolver"),
        .package(path: "../PluginFileInfo"),
        .package(path: "../PluginAboutSettings"),
        .package(path: "../PluginBanner"),
        .package(path: "../PluginIcon"),
        .package(path: "../PluginGitIgnore"),
        .package(path: "../PluginGitAutoPush"),
        .package(path: "../PluginLicense"),
        .package(path: "../PluginGitRemoteRepository"),
        .package(path: "../PluginDiagnosticsSettings"),
        .package(path: "../PluginGitSmartMerge"),
        .package(path: "../PluginGitLFS"),
        .package(path: "../PluginGitSubmodule"),
        .package(path: "../PluginGitRepositoryWatch"),
        .package(path: "../PluginGitWorktreePreheat"),
        .package(path: "../ProviderAutoPush"),
        .package(path: "../ProviderGit"),
        .package(path: "../ProviderGitConflictResolver"),
        .package(path: "../PluginGitLibGit2"),
        .package(path: "../PluginLogoCoffic"),
        .package(path: "../PluginLogoManager"),
        .package(path: "../PluginOpenAntigravity"),
        .package(path: "../PluginOpenCursor"),
        .package(path: "../PluginOpenFinder"),
        .package(path: "../PluginOpenGitHubDesktop"),
        .package(path: "../PluginOpenKiro"),
        .package(path: "../PluginOpenLumi"),
        .package(path: "../PluginOpenRemote"),
        .package(path: "../PluginOpenTerminal"),
        .package(path: "../PluginOpenTrae"),
        .package(path: "../PluginOpenVSCode"),
        .package(path: "../PluginOpenXcode"),
        .package(path: "../PluginPluginManager"),
        .package(path: "../PluginProjects"),
        .package(path: "../PluginSettingGeneral"),
        .package(path: "../PluginSettingView"),
        .package(path: "../PluginSettingsButton"),
        .package(path: "../PluginSidebarToggle"),
        .package(path: "../PluginStatusBar"),
        .package(url: "https://github.com/CofficLab/LumiPluginStorage.git", from: "1.0.0"),
        .package(path: "../PluginThemePack"),
        .package(path: "../ProviderActivity"),
        .package(path: "../ProviderCloneRepository"),
        .package(path: "../ProviderActivityHeatmap"),
        .package(path: "../ProviderProjectLanguages"),
        .package(url: "https://github.com/CofficLab/LumiProviders.git", from: "1.3.5"),
        .package(path: "../KitGit"),
        .package(path: "../ProviderCommitForm"),
        .package(path: "../PluginCommitToast"),
        .package(path: "../PluginCommitStatusBar"),
        .package(path: "../ProviderLogo"),
        .package(path: "../ProviderRootView"),
        .package(url: "https://github.com/CofficLab/LumiSettings.git", from: "1.0.1"),
        .package(path: "../ProviderProjects"),
        .package(path: "../ProviderSidebar"),
        .package(path: "../ProviderStatusBar"),
        .package(path: "../ProviderWorkspaceScene"),
        .package(path: "../PluginRootView"),
        .package(path: "../PluginRailView"),
        .package(url: "https://github.com/CofficLab/LumiPluginToast.git", from: "1.0.1"),
        .package(path: "../PluginWorktreeStatus"),
        .package(path: "../PluginProjectReadme"),
        .package(path: "../PluginWorktreeClean"),
    ],
    targets: [
        .target(
            name: "FactoryGitOK",
            dependencies: [
                .product(name: "LumiThemePack", package: "LumiThemePack"),
                .product(name: "KernelCore", package: "LumiKernel"),
                .product(name: "LumiLocalizationKit", package: "LumiLocalization"),
                .product(name: "LumiUI", package: "LumiUI"),
                .product(name: "ProviderContentView", package: "LumiProviders"),
                .product(name: "ProviderCloneRepository", package: "ProviderCloneRepository"),
                .product(name: "ProviderDocsView", package: "LumiProviders"),
                .product(name: "ProviderRootView", package: "ProviderRootView"),
                .product(name: "ProviderSettingView", package: "LumiSettings"),
                .product(name: "ProviderProjects", package: "ProviderProjects"),
                .product(name: "ProviderSidebar", package: "ProviderSidebar"),
                .product(name: "ProviderStorage", package: "LumiProviders"),
                .product(name: "ProviderStatusBar", package: "ProviderStatusBar"),
                .product(name: "ProviderWorkspaceScene", package: "ProviderWorkspaceScene"),
                .product(name: "ProviderGit", package: "ProviderGit"),
                .product(name: "ProviderTheme", package: "LumiProviders"),
                .product(name: "ProviderToast", package: "LumiProviders"),
                .product(name: "PluginRootView", package: "PluginRootView"),
                .product(name: "PluginCloneRepository", package: "PluginCloneRepository"),
                .product(name: "PluginRailView", package: "PluginRailView"),
                .product(name: "PluginToast", package: "LumiPluginToast"),
                .product(name: "PluginWorktreeStatus", package: "PluginWorktreeStatus"),
                .product(name: "PluginProjectReadme", package: "PluginProjectReadme"),
                .product(name: "PluginWorktreeClean", package: "PluginWorktreeClean"),
                .product(name: "ProviderToolbar", package: "LumiProviders"),
                .product(name: "PluginToolbar", package: "LumiProviders"),
                .product(name: "PluginActivityStatus", package: "PluginActivityStatus"),
                .product(name: "PluginCommand", package: "PluginCommand"),
                .product(name: "PluginCommitDetail", package: "PluginCommitDetail"),
                .product(name: "PluginActivityHeatmap", package: "PluginActivityHeatmap"),
                .product(name: "PluginProjectLanguages", package: "PluginProjectLanguages"),
                .product(name: "PluginCommitForm", package: "PluginCommitForm"),
                .product(name: "PluginCommitList", package: "PluginCommitList"),
                .product(name: "PluginGitDiff", package: "PluginGitDiff"),
                .product(name: "PluginGitBranchStatus", package: "PluginGitBranchStatus"),
                .product(name: "PluginGitUnpushedStatus", package: "PluginGitUnpushedStatus"),
                .product(name: "PluginGitUserSettings", package: "PluginGitUserSettings"),
                .product(name: "PluginGitNetworkSettings", package: "PluginGitNetworkSettings"),
                .product(name: "PluginGitRepositorySettings", package: "PluginGitRepositorySettings"),
                .product(name: "PluginGitCommitStyleSettings", package: "PluginGitCommitStyleSettings"),
                .product(name: "PluginGitStash", package: "PluginGitStash"),
                .product(name: "PluginGitConflictResolver", package: "PluginGitConflictResolver"),
                .product(name: "PluginFileInfo", package: "PluginFileInfo"),
                .product(name: "PluginAboutSettings", package: "PluginAboutSettings"),
                .product(name: "PluginBanner", package: "PluginBanner"),
                .product(name: "PluginIcon", package: "PluginIcon"),
                .product(name: "PluginGitIgnore", package: "PluginGitIgnore"),
                .product(name: "PluginGitAutoPush", package: "PluginGitAutoPush"),
                .product(name: "PluginLicense", package: "PluginLicense"),
                .product(name: "PluginGitRemoteRepository", package: "PluginGitRemoteRepository"),
                .product(name: "PluginDiagnosticsSettings", package: "PluginDiagnosticsSettings"),
                .product(name: "PluginGitSmartMerge", package: "PluginGitSmartMerge"),
                .product(name: "PluginGitLFS", package: "PluginGitLFS"),
                .product(name: "PluginGitSubmodule", package: "PluginGitSubmodule"),
                .product(name: "PluginGitRepositoryWatch", package: "PluginGitRepositoryWatch"),
                .product(name: "PluginGitWorktreePreheat", package: "PluginGitWorktreePreheat"),
                .product(name: "ProviderAutoPush", package: "ProviderAutoPush"),
                .product(name: "PluginGitLibGit2", package: "PluginGitLibGit2"),
                .product(name: "PluginLogoCoffic", package: "PluginLogoCoffic"),
                .product(name: "PluginLogoManager", package: "PluginLogoManager"),
                .product(name: "PluginOpenAntigravity", package: "PluginOpenAntigravity"),
                .product(name: "PluginOpenCursor", package: "PluginOpenCursor"),
                .product(name: "PluginOpenFinder", package: "PluginOpenFinder"),
                .product(name: "PluginOpenGitHubDesktop", package: "PluginOpenGitHubDesktop"),
                .product(name: "PluginOpenKiro", package: "PluginOpenKiro"),
                .product(name: "PluginOpenLumi", package: "PluginOpenLumi"),
                .product(name: "PluginOpenRemote", package: "PluginOpenRemote"),
                .product(name: "PluginOpenTerminal", package: "PluginOpenTerminal"),
                .product(name: "PluginOpenTrae", package: "PluginOpenTrae"),
                .product(name: "PluginOpenVSCode", package: "PluginOpenVSCode"),
                .product(name: "PluginOpenXcode", package: "PluginOpenXcode"),
                .product(name: "PluginPluginManager", package: "PluginPluginManager"),
                .product(name: "PluginProjects", package: "PluginProjects"),
                .product(name: "PluginSettingGeneral", package: "PluginSettingGeneral"),
                .product(name: "PluginSettingView", package: "PluginSettingView"),
                .product(name: "PluginSettingsButton", package: "PluginSettingsButton"),
                .product(name: "PluginSidebarToggle", package: "PluginSidebarToggle"),
                .product(name: "PluginStatusBar", package: "PluginStatusBar"),
                .product(name: "PluginStorage", package: "LumiPluginStorage"),
                .product(name: "PluginThemePack", package: "PluginThemePack"),
                .product(name: "ProviderCommand", package: "LumiProviders"),
                .product(name: "ProviderActivity", package: "ProviderActivity"),
                .product(name: "ProviderActivityHeatmap", package: "ProviderActivityHeatmap"),
                .product(name: "ProviderProjectLanguages", package: "ProviderProjectLanguages"),
                .product(name: "KitGit", package: "KitGit"),
                .product(name: "ProviderCommitForm", package: "ProviderCommitForm"),
                .product(name: "PluginCommitToast", package: "PluginCommitToast"),
                .product(name: "PluginCommitStatusBar", package: "PluginCommitStatusBar"),
                .product(name: "ProviderLogo", package: "ProviderLogo"),
                .product(name: "ProviderPluginControl", package: "LumiProviders"),
                .product(name: "ProviderPluginManaging", package: "LumiProviders"),
                .product(name: "ProviderRailView", package: "LumiProviders"),
            ],
            path: "Sources/FactoryGitOK",
            resources: [
                .process("../../Resources/Localizable.xcstrings")
            ],
            swiftSettings: [
                .swiftLanguageMode(.v5)
            ]
        ),
        .testTarget(
            name: "FactoryGitOKTests",
            dependencies: [
                "FactoryGitOK",
                .product(name: "KernelCore", package: "LumiKernel"),
                .product(name: "ProviderTheme", package: "LumiProviders"),
                .product(name: "LumiUI", package: "LumiUI"),
                .product(name: "ProviderStorage", package: "LumiProviders"),
                .product(name: "ProviderSettingView", package: "LumiSettings"),
                .product(name: "ProviderLogo", package: "ProviderLogo"),
                .product(name: "ProviderSidebar", package: "ProviderSidebar"),
                .product(name: "ProviderRailView", package: "LumiProviders"),
                .product(name: "ProviderCommand", package: "LumiProviders"),
                .product(name: "ProviderPluginManaging", package: "LumiProviders"),
                .product(name: "ProviderContentView", package: "LumiProviders"),
                .product(name: "ProviderDocsView", package: "LumiProviders"),
                .product(name: "ProviderToolbar", package: "LumiProviders"),
                .product(name: "ProviderStatusBar", package: "ProviderStatusBar"),
                .product(name: "ProviderRootView", package: "ProviderRootView"),
                .product(name: "ProviderToast", package: "LumiProviders"),
                .product(name: "KitGit", package: "KitGit"),
                .product(name: "ProviderGit", package: "ProviderGit"),
                .product(name: "ProviderGitConflictResolver", package: "ProviderGitConflictResolver"),
                .product(name: "PluginToast", package: "LumiPluginToast"),
                .product(name: "PluginCommitToast", package: "PluginCommitToast"),
                .product(name: "PluginCommitStatusBar", package: "PluginCommitStatusBar"),
                .product(name: "ProviderWorkspaceScene", package: "ProviderWorkspaceScene"),
            ],
            path: "Tests/FactoryGitOKTests",
            swiftSettings: [
                .swiftLanguageMode(.v5)
            ]
        ),
    ]
)
