// swift-tools-version: 6.0
import PackageDescription

let package = Package(
    name: "FactoryGitOK",
    defaultLocalization: "en",
    platforms: [
        .macOS(.v14),
    ],
    products: [
        .library(
            name: "FactoryGitOK",
            targets: ["FactoryGitOK"]
        ),
    ],
    dependencies: [
        .package(path: "../KernelCore"),
        .package(path: "../KitGitOKCore"),
        .package(path: "../FactoryCore"),
        .package(path: "../GitOKAppCore"),
        .package(path: "../GitOKUI"),
        .package(path: "../KitGitOKSupport"),
        .package(path: "../ProviderProject"),
        .package(path: "../../Plugins/PluginAboutSettings"),
        .package(path: "../../Plugins/PluginActivityStatus"),
        .package(path: "../../Plugins/PluginAppearanceSettings"),
        .package(path: "../../Plugins/PluginGitAutoPush"),
        .package(path: "../../Plugins/PluginGitBranch"),
        .package(path: "../../Plugins/PluginGitCleanStatus"),
        .package(path: "../../Plugins/PluginGitCommitList"),
        .package(path: "../../Plugins/PluginGitCommitStyleSettings"),
        .package(path: "../../Plugins/PluginGitConflictResolver"),
        .package(path: "../../Plugins/PluginDiagnosticsSettings"),
        .package(path: "../../Plugins/PluginFileInfo"),
        .package(path: "../../Plugins/PluginGitNetworkSettings"),
        .package(path: "../../Plugins/PluginGitUserSettings"),
        .package(path: "../../Plugins/PluginGitDetail"),
        .package(path: "../../Plugins/PluginGitIgnore"),
        .package(path: "../../Plugins/PluginGitLFS"),
        .package(path: "../../Plugins/PluginGitWatcher"),
        .package(path: "../../Plugins/PluginLicense"),
        .package(path: "../../Plugins/PluginOnboarding"),
        .package(path: "../../Plugins/PluginOpenAntigravity"),
        .package(path: "../../Plugins/PluginOpenCursor"),
        .package(path: "../../Plugins/PluginOpenFinder"),
        .package(path: "../../Plugins/PluginOpenGitHubDesktop"),
        .package(path: "../../Plugins/PluginOpenKiro"),
        .package(path: "../../Plugins/PluginOpenLumi"),
        .package(path: "../../Plugins/PluginOpenRemote"),
        .package(path: "../../Plugins/PluginOpenTerminal"),
        .package(path: "../../Plugins/PluginOpenTrae"),
        .package(path: "../../Plugins/PluginOpenVSCode"),
        .package(path: "../../Plugins/PluginOpenXcode"),
        .package(path: "../../Plugins/PluginProjects"),
        .package(path: "../../Plugins/PluginProjectPicker"),
        .package(path: "../../Plugins/PluginReadme"),
        .package(path: "../../Plugins/PluginGitRepositorySettings"),
        .package(path: "../../Plugins/PluginGitRemoteRepository"),
        .package(path: "../../Plugins/PluginSettingsButton"),
        .package(path: "../../Plugins/PluginGitSmartMerge"),
        .package(path: "../../Plugins/PluginGitStash"),
        .package(path: "../../Plugins/PluginGitSubmodule"),
        .package(path: "../../Plugins/PluginThemeAurora"),
        .package(path: "../../Plugins/PluginThemeDracula"),
        .package(path: "../../Plugins/PluginThemeEmber"),
        .package(path: "../../Plugins/PluginThemeGitHubLight"),
        .package(path: "../../Plugins/PluginThemeGitOK"),
        .package(path: "../../Plugins/PluginThemeGlacier"),
        .package(path: "../../Plugins/PluginThemeGraphite"),
        .package(path: "../../Plugins/PluginThemeHarbor"),
        .package(path: "../../Plugins/PluginThemeMatrix"),
        .package(path: "../../Plugins/PluginThemeMidnight"),
        .package(path: "../../Plugins/PluginThemeMountain"),
        .package(path: "../../Plugins/PluginThemeNebula"),
        .package(path: "../../Plugins/PluginThemeOneDark"),
        .package(path: "../../Plugins/PluginThemeOrchard"),
        .package(path: "../../Plugins/PluginThemeRiver"),
        .package(path: "../../Plugins/PluginThemeSpring"),
        .package(path: "../../Plugins/PluginThemeStatusBar"),
        .package(path: "../../Plugins/PluginThemeSummer"),
        .package(path: "../../Plugins/PluginThemeWinter"),
        .package(path: "../../Plugins/PluginThemeXcodeLight"),
        .package(path: "../../Plugins/PluginGitUnpushedStatus"),
        .package(path: "../../Plugins/PluginGitWorkingState"),
    ],
    targets: [
        .target(
            name: "FactoryGitOK",
            dependencies: [
                "KernelCore",
                "KitGitOKCore",
                "FactoryCore",
                "GitOKAppCore",
                "GitOKUI",
                "KitGitOKSupport",
                "ProviderProject",
                .product(name: "PluginAboutSettings", package: "PluginAboutSettings"),
                .product(name: "PluginActivityStatus", package: "PluginActivityStatus"),
                .product(name: "PluginAppearanceSettings", package: "PluginAppearanceSettings"),
                .product(name: "PluginGitAutoPush", package: "PluginGitAutoPush"),
                .product(name: "PluginGitBranch", package: "PluginGitBranch"),
                .product(name: "PluginGitCleanStatus", package: "PluginGitCleanStatus"),
                .product(name: "PluginGitCommitList", package: "PluginGitCommitList"),
                .product(name: "PluginGitCommitStyleSettings", package: "PluginGitCommitStyleSettings"),
                .product(name: "PluginGitConflictResolver", package: "PluginGitConflictResolver"),
                .product(name: "PluginDiagnosticsSettings", package: "PluginDiagnosticsSettings"),
                .product(name: "PluginFileInfo", package: "PluginFileInfo"),
                .product(name: "PluginGitNetworkSettings", package: "PluginGitNetworkSettings"),
                .product(name: "PluginGitUserSettings", package: "PluginGitUserSettings"),
                .product(name: "PluginGitDetail", package: "PluginGitDetail"),
                .product(name: "PluginGitIgnore", package: "PluginGitIgnore"),
                .product(name: "PluginGitLFS", package: "PluginGitLFS"),
                .product(name: "PluginGitWatcher", package: "PluginGitWatcher"),
                .product(name: "PluginLicense", package: "PluginLicense"),
                .product(name: "PluginOnboarding", package: "PluginOnboarding"),
                .product(name: "PluginOpenAntigravity", package: "PluginOpenAntigravity"),
                .product(name: "PluginOpenCursor", package: "PluginOpenCursor"),
                .product(name: "PluginOpenFinder", package: "PluginOpenFinder"),
                .product(name: "PluginOpenGitHubDesktop", package: "PluginOpenGitHubDesktop"),
                .product(name: "PluginOpenKiro", package: "PluginOpenKiro"),
                .product(name: "PluginOpenLumi", package: "PluginOpenLumi"),
                .product(name: "PluginOpenRemote", package: "PluginOpenRemote"),
                .product(name: "PluginOpenTerminal", package: "PluginOpenTerminal"),
                .product(name: "PluginOpenTrae", package: "PluginOpenTrae"),
                .product(name: "PluginOpenVSCode", package: "PluginOpenVSCode"),
                .product(name: "PluginOpenXcode", package: "PluginOpenXcode"),
                .product(name: "PluginProjects", package: "PluginProjects"),
                .product(name: "PluginProjectPicker", package: "PluginProjectPicker"),
                .product(name: "PluginReadme", package: "PluginReadme"),
                .product(name: "PluginGitRepositorySettings", package: "PluginGitRepositorySettings"),
                .product(name: "PluginGitRemoteRepository", package: "PluginGitRemoteRepository"),
                .product(name: "PluginSettingsButton", package: "PluginSettingsButton"),
                .product(name: "PluginGitSmartMerge", package: "PluginGitSmartMerge"),
                .product(name: "PluginGitStash", package: "PluginGitStash"),
                .product(name: "PluginGitSubmodule", package: "PluginGitSubmodule"),
                .product(name: "PluginThemeAurora", package: "PluginThemeAurora"),
                .product(name: "PluginThemeDracula", package: "PluginThemeDracula"),
                .product(name: "PluginThemeEmber", package: "PluginThemeEmber"),
                .product(name: "PluginThemeGitHubLight", package: "PluginThemeGitHubLight"),
                .product(name: "PluginThemeGitOK", package: "PluginThemeGitOK"),
                .product(name: "PluginThemeGlacier", package: "PluginThemeGlacier"),
                .product(name: "PluginThemeGraphite", package: "PluginThemeGraphite"),
                .product(name: "PluginThemeHarbor", package: "PluginThemeHarbor"),
                .product(name: "PluginThemeMatrix", package: "PluginThemeMatrix"),
                .product(name: "PluginThemeMidnight", package: "PluginThemeMidnight"),
                .product(name: "PluginThemeMountain", package: "PluginThemeMountain"),
                .product(name: "PluginThemeNebula", package: "PluginThemeNebula"),
                .product(name: "PluginThemeOneDark", package: "PluginThemeOneDark"),
                .product(name: "PluginThemeOrchard", package: "PluginThemeOrchard"),
                .product(name: "PluginThemeRiver", package: "PluginThemeRiver"),
                .product(name: "PluginThemeSpring", package: "PluginThemeSpring"),
                .product(name: "PluginThemeStatusBar", package: "PluginThemeStatusBar"),
                .product(name: "PluginThemeSummer", package: "PluginThemeSummer"),
                .product(name: "PluginThemeWinter", package: "PluginThemeWinter"),
                .product(name: "PluginThemeXcodeLight", package: "PluginThemeXcodeLight"),
                .product(name: "PluginGitUnpushedStatus", package: "PluginGitUnpushedStatus"),
                .product(name: "PluginGitWorkingState", package: "PluginGitWorkingState"),
            ],
            path: "Sources",
            resources: [.process("Localizable.xcstrings")]
        ),
        .testTarget(
            name: "FactoryGitOKTests",
            dependencies: ["FactoryGitOK"],
            path: "Tests"
        ),
    ]
)
