// This file is generated by Scripts/generate_plugin_registry.sh.
// Do not edit by hand.

import GitOKCoreKit
import PluginOpenAntigravity
import PluginOpenCursor
import PluginOpenFinder
import PluginOpenGitHubDesktop
import PluginOpenKiro
import PluginOpenRemote
import PluginOpenTerminal
import PluginOpenTrae
import PluginOpenVSCode
import PluginOpenXcode

/// Auto-generated plugin registry.
/// Registers plugin adapters generated from enabled plugin packages.
public enum GeneratedPluginRegistry {
    public static let hasDefaultAdapters = true

    /// Register default plugin adapters for all enabled plugin packages.
    ///
    /// - Parameters:
    ///   - adapterFactory: Factory supplied by the host app to preserve app-specific bridging.
    ///   - register: Closure that handles the actual registration.
    @MainActor
    public static func registerDefaultAdapters(
        adapterFactory: any GitOKPluginAdapterFactory,
        _ register: (any SuperPlugin) -> Void
    ) {
        if OpenAntigravityPlugin.shouldRegister { register(adapterFactory.makeAdapter(for: OpenAntigravityPlugin.shared)) }
        if OpenCursorPlugin.shouldRegister { register(adapterFactory.makeAdapter(for: OpenCursorPlugin.shared)) }
        if OpenFinderPlugin.shouldRegister { register(adapterFactory.makeAdapter(for: OpenFinderPlugin.shared)) }
        if OpenGitHubDesktopPlugin.shouldRegister { register(adapterFactory.makeAdapter(for: OpenGitHubDesktopPlugin.shared)) }
        if OpenKiroPlugin.shouldRegister { register(adapterFactory.makeAdapter(for: OpenKiroPlugin.shared)) }
        if OpenRemotePlugin.shouldRegister { register(adapterFactory.makeAdapter(for: OpenRemotePlugin.shared)) }
        if OpenTerminalPlugin.shouldRegister { register(adapterFactory.makeAdapter(for: OpenTerminalPlugin.shared)) }
        if OpenTraePlugin.shouldRegister { register(adapterFactory.makeAdapter(for: OpenTraePlugin.shared)) }
        if OpenVSCodePlugin.shouldRegister { register(adapterFactory.makeAdapter(for: OpenVSCodePlugin.shared)) }
        if OpenXcodePlugin.shouldRegister { register(adapterFactory.makeAdapter(for: OpenXcodePlugin.shared)) }
    }
}
