// This file is generated by Scripts/generate_plugin_registry.sh.
// Do not edit by hand.

import GitOKCoreKit

/// Auto-generated plugin registry.
/// Registers plugin adapters generated from enabled plugin packages.
public enum GeneratedPluginRegistry {
    public static let hasDefaultAdapters = false

    /// Register default plugin adapters for all enabled plugin packages.
    ///
    /// - Parameters:
    ///   - adapterFactory: Factory supplied by the host app to preserve app-specific bridging.
    ///   - register: Closure that handles the actual registration.
    @MainActor
    public static func registerDefaultAdapters(
        adapterFactory: some GitOKPluginAdapterFactory,
        _ register: (any SuperPlugin) -> Void
    ) {
    }
}
