// swift-tools-version: 6.0
import PackageDescription

let package = Package(
    name: "GitOKPluginRegistry",
    defaultLocalization: "en",
    platforms: [
        .macOS(.v14),
    ],
    products: [
        .library(
            name: "GitOKPluginRegistry",
            targets: ["GitOKPluginRegistry"]
        ),
    ],
    dependencies: [
        .package(path: "../GitOKCoreKit"),
        .package(path: "../../Plugins/ActivityStatusPlugin"),
        .package(path: "../../Plugins/AutoPushPlugin"),
        .package(path: "../../Plugins/BannerPlugin"),
        .package(path: "../../Plugins/BannerTabPlugin"),
        .package(path: "../../Plugins/BranchPlugin"),
        .package(path: "../../Plugins/CleanStatusPlugin"),
        .package(path: "../../Plugins/CommitPlugin"),
        .package(path: "../../Plugins/ConflictResolverPlugin"),
        .package(path: "../../Plugins/FileInfoPlugin"),
        .package(path: "../../Plugins/GitDetailPlugin"),
        .package(path: "../../Plugins/GitIgnorePlugin"),
        .package(path: "../../Plugins/GitLFSPlugin"),
        .package(path: "../../Plugins/GitTabPlugin"),
        .package(path: "../../Plugins/GitWatcherPlugin"),
        .package(path: "../../Plugins/IconPlugin"),
        .package(path: "../../Plugins/IconTabPlugin"),
        .package(path: "../../Plugins/LicensePlugin"),
        .package(path: "../../Plugins/OpenAntigravityPlugin"),
        .package(path: "../../Plugins/OpenCursorPlugin"),
        .package(path: "../../Plugins/OpenFinderPlugin"),
        .package(path: "../../Plugins/OpenGitHubDesktopPlugin"),
        .package(path: "../../Plugins/OpenKiroPlugin"),
        .package(path: "../../Plugins/OpenRemotePlugin"),
        .package(path: "../../Plugins/OpenTerminalPlugin"),
        .package(path: "../../Plugins/OpenTraePlugin"),
        .package(path: "../../Plugins/OpenVSCodePlugin"),
        .package(path: "../../Plugins/OpenXcodePlugin"),
        .package(path: "../../Plugins/ProjectPickerPlugin"),
        .package(path: "../../Plugins/ReadmePlugin"),
        .package(path: "../../Plugins/RemoteRepositoryPlugin"),
        .package(path: "../../Plugins/SettingsButtonPlugin"),
        .package(path: "../../Plugins/SmartMergePlugin"),
        .package(path: "../../Plugins/StashPlugin"),
        .package(path: "../../Plugins/SubmodulePlugin"),
        .package(path: "../../Plugins/ThemeAuroraPlugin"),
        .package(path: "../../Plugins/ThemeDraculaPlugin"),
        .package(path: "../../Plugins/ThemeEmberPlugin"),
        .package(path: "../../Plugins/ThemeGitHubLightPlugin"),
        .package(path: "../../Plugins/ThemeGitOKPlugin"),
        .package(path: "../../Plugins/ThemeGlacierPlugin"),
        .package(path: "../../Plugins/ThemeGraphitePlugin"),
        .package(path: "../../Plugins/ThemeHarborPlugin"),
        .package(path: "../../Plugins/ThemeMatrixPlugin"),
        .package(path: "../../Plugins/ThemeMidnightPlugin"),
        .package(path: "../../Plugins/ThemeMountainPlugin"),
        .package(path: "../../Plugins/ThemeNebulaPlugin"),
        .package(path: "../../Plugins/ThemeOneDarkPlugin"),
        .package(path: "../../Plugins/ThemeOrchardPlugin"),
        .package(path: "../../Plugins/ThemeRiverPlugin"),
        .package(path: "../../Plugins/ThemeSpringPlugin"),
        .package(path: "../../Plugins/ThemeStatusBarPlugin"),
        .package(path: "../../Plugins/ThemeSummerPlugin"),
        .package(path: "../../Plugins/ThemeWinterPlugin"),
        .package(path: "../../Plugins/ThemeXcodeLightPlugin"),
        .package(path: "../../Plugins/UnpushedStatusPlugin"),
    ],
    targets: [
        .target(
            name: "GitOKPluginRegistry",
            dependencies: [
                "GitOKCoreKit",
                "ActivityStatusPlugin",
                "AutoPushPlugin",
                "BannerPlugin",
                "BannerTabPlugin",
                "BranchPlugin",
                "CleanStatusPlugin",
                "CommitPlugin",
                "ConflictResolverPlugin",
                "FileInfoPlugin",
                "GitDetailPlugin",
                "GitIgnorePlugin",
                "GitLFSPlugin",
                "GitTabPlugin",
                "GitWatcherPlugin",
                "IconPlugin",
                "IconTabPlugin",
                "LicensePlugin",
                "OpenAntigravityPlugin",
                "OpenCursorPlugin",
                "OpenFinderPlugin",
                "OpenGitHubDesktopPlugin",
                "OpenKiroPlugin",
                "OpenRemotePlugin",
                "OpenTerminalPlugin",
                "OpenTraePlugin",
                "OpenVSCodePlugin",
                "OpenXcodePlugin",
                "ProjectPickerPlugin",
                "ReadmePlugin",
                "RemoteRepositoryPlugin",
                "SettingsButtonPlugin",
                "SmartMergePlugin",
                "StashPlugin",
                "SubmodulePlugin",
                "ThemeAuroraPlugin",
                "ThemeDraculaPlugin",
                "ThemeEmberPlugin",
                "ThemeGitHubLightPlugin",
                "ThemeGitOKPlugin",
                "ThemeGlacierPlugin",
                "ThemeGraphitePlugin",
                "ThemeHarborPlugin",
                "ThemeMatrixPlugin",
                "ThemeMidnightPlugin",
                "ThemeMountainPlugin",
                "ThemeNebulaPlugin",
                "ThemeOneDarkPlugin",
                "ThemeOrchardPlugin",
                "ThemeRiverPlugin",
                "ThemeSpringPlugin",
                "ThemeStatusBarPlugin",
                "ThemeSummerPlugin",
                "ThemeWinterPlugin",
                "ThemeXcodeLightPlugin",
                "UnpushedStatusPlugin",
            ],
            path: "Sources",
            resources: [.process("Localizable.xcstrings")]
        ),
    ]
)
