// swift-tools-version: 6.0
import PackageDescription

let package = Package(
    name: "GitOKPluginRegistry",
    platforms: [
        .macOS(.v15),
    ],
    products: [
        .library(
            name: "GitOKPluginRegistry",
            targets: ["GitOKPluginRegistry"]
        ),
    ],
    dependencies: [
        .package(path: "../GitOKCoreKit"),
        .package(path: "../../Plugins/PluginActivityStatus"),
        .package(path: "../../Plugins/PluginAutoPush"),
        .package(path: "../../Plugins/PluginBanner"),
        .package(path: "../../Plugins/PluginBannerTab"),
        .package(path: "../../Plugins/PluginBranch"),
        .package(path: "../../Plugins/PluginCleanStatus"),
        .package(path: "../../Plugins/PluginCommit"),
        .package(path: "../../Plugins/PluginConflictResolver"),
        .package(path: "../../Plugins/PluginFileInfo"),
        .package(path: "../../Plugins/PluginGitClone"),
        .package(path: "../../Plugins/PluginGitDetail"),
        .package(path: "../../Plugins/PluginGitIgnore"),
        .package(path: "../../Plugins/PluginGitLFS"),
        .package(path: "../../Plugins/PluginGitPull"),
        .package(path: "../../Plugins/PluginGitPush"),
        .package(path: "../../Plugins/PluginGitSync"),
        .package(path: "../../Plugins/PluginGitTab"),
        .package(path: "../../Plugins/PluginGitWatcher"),
        .package(path: "../../Plugins/PluginIcon"),
        .package(path: "../../Plugins/PluginIconTab"),
        .package(path: "../../Plugins/PluginLicense"),
        .package(path: "../../Plugins/PluginOpenAntigravity"),
        .package(path: "../../Plugins/PluginOpenCursor"),
        .package(path: "../../Plugins/PluginOpenFinder"),
        .package(path: "../../Plugins/PluginOpenGitHubDesktop"),
        .package(path: "../../Plugins/PluginOpenKiro"),
        .package(path: "../../Plugins/PluginOpenRemote"),
        .package(path: "../../Plugins/PluginOpenTerminal"),
        .package(path: "../../Plugins/PluginOpenTrae"),
        .package(path: "../../Plugins/PluginOpenVSCode"),
        .package(path: "../../Plugins/PluginOpenXcode"),
        .package(path: "../../Plugins/PluginProjectPicker"),
        .package(path: "../../Plugins/PluginReadme"),
        .package(path: "../../Plugins/PluginRemoteRepository"),
        .package(path: "../../Plugins/PluginSettingsButton"),
        .package(path: "../../Plugins/PluginSmartMerge"),
        .package(path: "../../Plugins/PluginStash"),
        .package(path: "../../Plugins/PluginSubmodule"),
        .package(path: "../../Plugins/PluginThemeAurora"),
        .package(path: "../../Plugins/PluginThemeDracula"),
        .package(path: "../../Plugins/PluginThemeEmber"),
        .package(path: "../../Plugins/PluginThemeGitHubLight"),
        .package(path: "../../Plugins/PluginThemeGitOK"),
        .package(path: "../../Plugins/PluginThemeGlacier"),
        .package(path: "../../Plugins/PluginThemeGraphite"),
        .package(path: "../../Plugins/PluginThemeHarbor"),
        .package(path: "../../Plugins/PluginThemeMatrix"),
        .package(path: "../../Plugins/PluginThemeMidnight"),
        .package(path: "../../Plugins/PluginThemeMountain"),
        .package(path: "../../Plugins/PluginThemeNebula"),
        .package(path: "../../Plugins/PluginThemeOneDark"),
        .package(path: "../../Plugins/PluginThemeOrchard"),
        .package(path: "../../Plugins/PluginThemeRiver"),
        .package(path: "../../Plugins/PluginThemeSpring"),
        .package(path: "../../Plugins/PluginThemeStatusBar"),
        .package(path: "../../Plugins/PluginThemeSummer"),
        .package(path: "../../Plugins/PluginThemeWinter"),
        .package(path: "../../Plugins/PluginThemeXcodeLight"),
        .package(path: "../../Plugins/PluginUnpushedStatus"),
    ],
    targets: [
        .target(
            name: "GitOKPluginRegistry",
            dependencies: [
                "GitOKCoreKit",
                "PluginActivityStatus",
                "PluginAutoPush",
                "PluginBanner",
                "PluginBannerTab",
                "PluginBranch",
                "PluginCleanStatus",
                "PluginCommit",
                "PluginConflictResolver",
                "PluginFileInfo",
                "PluginGitClone",
                "PluginGitDetail",
                "PluginGitIgnore",
                "PluginGitLFS",
                "PluginGitPull",
                "PluginGitPush",
                "PluginGitSync",
                "PluginGitTab",
                "PluginGitWatcher",
                "PluginIcon",
                "PluginIconTab",
                "PluginLicense",
                "PluginOpenAntigravity",
                "PluginOpenCursor",
                "PluginOpenFinder",
                "PluginOpenGitHubDesktop",
                "PluginOpenKiro",
                "PluginOpenRemote",
                "PluginOpenTerminal",
                "PluginOpenTrae",
                "PluginOpenVSCode",
                "PluginOpenXcode",
                "PluginProjectPicker",
                "PluginReadme",
                "PluginRemoteRepository",
                "PluginSettingsButton",
                "PluginSmartMerge",
                "PluginStash",
                "PluginSubmodule",
                "PluginThemeAurora",
                "PluginThemeDracula",
                "PluginThemeEmber",
                "PluginThemeGitHubLight",
                "PluginThemeGitOK",
                "PluginThemeGlacier",
                "PluginThemeGraphite",
                "PluginThemeHarbor",
                "PluginThemeMatrix",
                "PluginThemeMidnight",
                "PluginThemeMountain",
                "PluginThemeNebula",
                "PluginThemeOneDark",
                "PluginThemeOrchard",
                "PluginThemeRiver",
                "PluginThemeSpring",
                "PluginThemeStatusBar",
                "PluginThemeSummer",
                "PluginThemeWinter",
                "PluginThemeXcodeLight",
                "PluginUnpushedStatus",
            ],
            path: "Sources/GitOKPluginRegistry"
        ),
    ]
)
