// swift-tools-version: 6.0
import PackageDescription

let package = Package(
    name: "GitOKPluginRegistry",
    defaultLocalization: "en",
    platforms: [
        .macOS(.v14),
    ],
    products: [
        .library(
            name: "GitOKPluginRegistry",
            targets: ["GitOKPluginRegistry"]
        ),
    ],
    dependencies: [
        .package(path: "../GitOKCoreKit"),
        .package(path: "../ProjectKit"),
        .package(path: "../../Plugins/AboutSettingsPlugin"),
        .package(path: "../../Plugins/ActivityStatusPlugin"),
        .package(path: "../../Plugins/AppearanceSettingsPlugin"),
        .package(path: "../../Plugins/GitAutoPushPlugin"),
        .package(path: "../../Plugins/BannerPlugin"),
        .package(path: "../../Plugins/GitBranchPlugin"),
        .package(path: "../../Plugins/GitCleanStatusPlugin"),
        .package(path: "../../Plugins/GitCommitListPlugin"),
        .package(path: "../../Plugins/GitCommitStyleSettingsPlugin"),
        .package(path: "../../Plugins/GitConflictResolverPlugin"),
        .package(path: "../../Plugins/DiagnosticsSettingsPlugin"),
        .package(path: "../../Plugins/FileInfoPlugin"),
        .package(path: "../../Plugins/GitNetworkSettingsPlugin"),
        .package(path: "../../Plugins/GitUserSettingsPlugin"),
        .package(path: "../../Plugins/GitDetailPlugin"),
        .package(path: "../../Plugins/GitIgnorePlugin"),
        .package(path: "../../Plugins/GitLFSPlugin"),
        .package(path: "../../Plugins/GitWatcherPlugin"),
        .package(path: "../../Plugins/IconPlugin"),
        .package(path: "../../Plugins/LicensePlugin"),
        .package(path: "../../Plugins/OnboardingPlugin"),
        .package(path: "../../Plugins/OpenAntigravityPlugin"),
        .package(path: "../../Plugins/OpenCursorPlugin"),
        .package(path: "../../Plugins/OpenFinderPlugin"),
        .package(path: "../../Plugins/OpenGitHubDesktopPlugin"),
        .package(path: "../../Plugins/OpenKiroPlugin"),
        .package(path: "../../Plugins/OpenLumiPlugin"),
        .package(path: "../../Plugins/OpenRemotePlugin"),
        .package(path: "../../Plugins/OpenTerminalPlugin"),
        .package(path: "../../Plugins/OpenTraePlugin"),
        .package(path: "../../Plugins/OpenVSCodePlugin"),
        .package(path: "../../Plugins/OpenXcodePlugin"),
        .package(path: "../../Plugins/ProjectsPlugin"),
        .package(path: "../../Plugins/ProjectPickerPlugin"),
        .package(path: "../../Plugins/ReadmePlugin"),
        .package(path: "../../Plugins/GitRepositorySettingsPlugin"),
        .package(path: "../../Plugins/GitRemoteRepositoryPlugin"),
        .package(path: "../../Plugins/SettingsButtonPlugin"),
        .package(path: "../../Plugins/GitSmartMergePlugin"),
        .package(path: "../../Plugins/GitStashPlugin"),
        .package(path: "../../Plugins/GitSubmodulePlugin"),
        .package(path: "../../Plugins/ThemeAuroraPlugin"),
        .package(path: "../../Plugins/ThemeDraculaPlugin"),
        .package(path: "../../Plugins/ThemeEmberPlugin"),
        .package(path: "../../Plugins/ThemeGitHubLightPlugin"),
        .package(path: "../../Plugins/ThemeGitOKPlugin"),
        .package(path: "../../Plugins/ThemeGlacierPlugin"),
        .package(path: "../../Plugins/ThemeGraphitePlugin"),
        .package(path: "../../Plugins/ThemeHarborPlugin"),
        .package(path: "../../Plugins/ThemeMatrixPlugin"),
        .package(path: "../../Plugins/ThemeMidnightPlugin"),
        .package(path: "../../Plugins/ThemeMountainPlugin"),
        .package(path: "../../Plugins/ThemeNebulaPlugin"),
        .package(path: "../../Plugins/ThemeOneDarkPlugin"),
        .package(path: "../../Plugins/ThemeOrchardPlugin"),
        .package(path: "../../Plugins/ThemeRiverPlugin"),
        .package(path: "../../Plugins/ThemeSpringPlugin"),
        .package(path: "../../Plugins/ThemeStatusBarPlugin"),
        .package(path: "../../Plugins/ThemeSummerPlugin"),
        .package(path: "../../Plugins/ThemeWinterPlugin"),
        .package(path: "../../Plugins/ThemeXcodeLightPlugin"),
        .package(path: "../../Plugins/GitUnpushedStatusPlugin"),
        .package(path: "../../Plugins/GitWorkingStatePlugin"),
    ],
    targets: [
        .target(
            name: "GitOKPluginRegistry",
            dependencies: [
                "GitOKCoreKit",
                "ProjectKit",
                "AboutSettingsPlugin",
                "ActivityStatusPlugin",
                "AppearanceSettingsPlugin",
                "GitAutoPushPlugin",
                "BannerPlugin",
                "GitBranchPlugin",
                "GitCleanStatusPlugin",
                "GitCommitListPlugin",
                "GitCommitStyleSettingsPlugin",
                "GitConflictResolverPlugin",
                "DiagnosticsSettingsPlugin",
                "FileInfoPlugin",
                "GitNetworkSettingsPlugin",
                "GitUserSettingsPlugin",
                "GitDetailPlugin",
                "GitIgnorePlugin",
                "GitLFSPlugin",
                "GitWatcherPlugin",
                "IconPlugin",
                "LicensePlugin",
                "OnboardingPlugin",
                "OpenAntigravityPlugin",
                "OpenCursorPlugin",
                "OpenFinderPlugin",
                "OpenGitHubDesktopPlugin",
                "OpenKiroPlugin",
                "OpenLumiPlugin",
                "OpenRemotePlugin",
                "OpenTerminalPlugin",
                "OpenTraePlugin",
                "OpenVSCodePlugin",
                "OpenXcodePlugin",
                "ProjectsPlugin",
                "ProjectPickerPlugin",
                "ReadmePlugin",
                "GitRepositorySettingsPlugin",
                "GitRemoteRepositoryPlugin",
                "SettingsButtonPlugin",
                "GitSmartMergePlugin",
                "GitStashPlugin",
                "GitSubmodulePlugin",
                "ThemeAuroraPlugin",
                "ThemeDraculaPlugin",
                "ThemeEmberPlugin",
                "ThemeGitHubLightPlugin",
                "ThemeGitOKPlugin",
                "ThemeGlacierPlugin",
                "ThemeGraphitePlugin",
                "ThemeHarborPlugin",
                "ThemeMatrixPlugin",
                "ThemeMidnightPlugin",
                "ThemeMountainPlugin",
                "ThemeNebulaPlugin",
                "ThemeOneDarkPlugin",
                "ThemeOrchardPlugin",
                "ThemeRiverPlugin",
                "ThemeSpringPlugin",
                "ThemeStatusBarPlugin",
                "ThemeSummerPlugin",
                "ThemeWinterPlugin",
                "ThemeXcodeLightPlugin",
                "GitUnpushedStatusPlugin",
                "GitWorkingStatePlugin",
            ],
            path: "Sources",
            resources: [.process("Localizable.xcstrings")]
        ),
    ]
)
