diff --git a/GitOK/Helper/CloudHandler.swift b/GitOK/Helper/CloudHandler.swift
deleted file mode 100644
index 8f8bc93..0000000
--- a/GitOK/Helper/CloudHandler.swift
+++ /dev/null
@@ -1,135 +0,0 @@
-import Foundation
-import OSLog
-
-actor CloudHandler {
-    let coordinator = NSFileCoordinator()
-    var filePresenters: [URL: FilePresenter] = [:]
-
-    func write(targetURL: URL, data: Data) throws {
-        var coordinationError: NSError?
-        var writeError: Error?
-
-        // 使用 coordinationError 变量来捕获 coordinate 方法的错误信息。
-        // 如果不提供一个 NSError 指针，协调过程中发生的错误将无法被捕获和处理。
-        coordinator.coordinate(writingItemAt: targetURL, options: [.forDeleting], error: &coordinationError) { url in
-            do {
-                try data.write(to: url, options: .atomic)
-            } catch {
-                writeError = error
-            }
-        }
-
-        // 在闭包外部检查是否有错误发生
-        if let error = writeError {
-            throw error
-        }
-
-        // 检查协调过程中是否发生了错误
-        if let coordinationError = coordinationError {
-            throw coordinationError
-        }
-    }
-
-    func read(url: URL) throws -> Data {
-        var coordinationError: NSError?
-        var readData: Data?
-        var readError: Error?
-
-        coordinator.coordinate(readingItemAt: url, options: [], error: &coordinationError) { url in
-            do {
-                readData = try Data(contentsOf: url)
-            } catch {
-                readError = error
-            }
-        }
-
-        // 检查读取过程中是否发生了错误
-        if let error = readError {
-            throw error
-        }
-
-        // 检查协调过程中是否发生了错误
-        if let coordinationError = coordinationError {
-            throw coordinationError
-        }
-
-        // 确保读取到的数据不为空
-        guard let data = readData else {
-            throw NSError(domain: "CloudDocumentsHandlerError", code: 0, userInfo: [NSLocalizedDescriptionKey: "No data was read from the file."])
-        }
-
-        return data
-    }
-
-    func startMonitoringFile(at url: URL, onDidChange: (() -> Void)? = nil) {
-        let defaultOnDidChange: () -> Void = {
-            os_log("🍋 CloudDocumentsHelper::onDidChange")
-        }
-        let presenter = FilePresenter(fileURL: url)
-        presenter.onDidChange = onDidChange ?? defaultOnDidChange
-        filePresenters[url] = presenter
-    }
-
-    func stopMonitoringFile(at url: URL) {
-        if let presenter = filePresenters[url] {
-            NSFileCoordinator.removeFilePresenter(presenter)
-        }
-        filePresenters[url] = nil
-    }
-}
-
-extension CloudHandler {
-    func download(url: URL) throws {
-        var coordinationError: NSError?
-        var downloadError: Error?
-
-        coordinator.coordinate(writingItemAt: url, options: [], error: &coordinationError) { newURL in
-            do {
-                try FileManager.default.startDownloadingUbiquitousItem(at: newURL)
-            } catch {
-                downloadError = error
-            }
-        }
-
-        // 检查下载过程中是否发生了错误
-        if let error = downloadError {
-            throw error
-        }
-
-        // 检查协调过程中是否发生了错误
-        if let coordinationError = coordinationError {
-            throw coordinationError
-        }
-    }
-
-    func evict(url: URL) throws {
-        do {
-            try FileManager.default.evictUbiquitousItem(at: url)
-        } catch {
-            throw error
-        }
-    }
-
-    func moveFile(at sourceURL: URL, to destinationURL: URL) throws {
-        var coordinationError: NSError?
-        var moveError: Error?
-
-        coordinator.coordinate(writingItemAt: sourceURL, options: .forMoving, writingItemAt: destinationURL, options: .forReplacing, error: &coordinationError) { newSourceURL, newDestinationURL in
-            do {
-                try FileManager.default.moveItem(at: newSourceURL, to: newDestinationURL)
-            } catch {
-                moveError = error
-            }
-        }
-
-        // 检查移动过程中是否发生了错误
-        if let error = moveError {
-            throw error
-        }
-
-        // 检查协调过程中是否发生了错误
-        if let coordinationError = coordinationError {
-            throw coordinationError
-        }
-    }
-}
