#!/bin/sh
set -eu

# ==============================================================================
# generate_plugin_registry.sh
#
# Scans plugin packages for enabled types conforming to GitOKPlugin and
# generates APP/Generated/GeneratedPluginRegistry.swift.
#
# Inspired by Cisum's Scripts/generate_plugin_registry.sh.
# ==============================================================================

ROOT_DIR="${SRCROOT:-$(cd "$(dirname "$0")/.." && pwd)}"
PLUGINS_DIR="$ROOT_DIR/Plugins"
OUTPUT="$ROOT_DIR/APP/Generated/GeneratedPluginRegistry.swift"
TMP_OUTPUT="$OUTPUT.tmp"

mkdir -p "$(dirname "$OUTPUT")"

# ---------------------------------------------------------------------------
# 1. Scan for GitOKPlugin conformances
#    Pattern: public struct <Name>Plugin: GitOKPlugin {
# ---------------------------------------------------------------------------

registry_entries=$(
    find "$PLUGINS_DIR" -mindepth 4 -maxdepth 4 -path "$PLUGINS_DIR/Plugin*/Sources/*/*.swift" -print |
    sort |
    while IFS= read -r plugin_file; do
        struct_name=$(sed -n 's/^[[:space:]]*public struct \([A-Za-z0-9_]*Plugin\):.*GitOKPlugin.*/\1/p' "$plugin_file" | head -1)
        [ -n "$struct_name" ] || continue

        if grep -Eq 'policy:[[:space:]]*\.disabled' "$plugin_file"; then
            continue
        fi

        package_name=$(printf '%s\n' "$plugin_file" | sed "s#^$PLUGINS_DIR/##; s#/.*##")
        [ -n "$package_name" ] || continue

        printf '%s|%s\n' "$struct_name" "$package_name"
    done
)

registry_entries=$(printf '%s\n' "$registry_entries" | awk 'NF > 0' | sort -u)
registry_imports=$(printf '%s\n' "$registry_entries" | awk -F'|' '{ print $2 }' | sort -u)

# ---------------------------------------------------------------------------
# 2. Generate the Swift file
# ---------------------------------------------------------------------------

{
    printf '// This file is generated by Scripts/generate_plugin_registry.sh.\n'
    printf '// Do not edit by hand.\n\n'
    printf 'import GitOKCoreKit\n'
    printf '%s\n' "$registry_imports" |
    while IFS= read -r package_name; do
        [ -n "$package_name" ] || continue
        printf 'import %s\n' "$package_name"
    done
    printf '\n'
    printf '/// Auto-generated plugin registry.\n'
    printf '/// Registers plugin adapters generated from enabled plugin packages.\n'
    printf 'enum GeneratedPluginRegistry {\n'
    if [ -n "$registry_entries" ]; then
        printf '    static let hasDefaultAdapters = true\n\n'
    else
        printf '    static let hasDefaultAdapters = false\n\n'
    fi
    printf '    /// Register default `PluginAdapter` instances for all plugins.\n'
    printf '    /// Each adapter preserves the concrete generic type so that\n'
    printf '    /// `shouldRegister` / `order` etc. are resolved at compile time.\n'
    printf '    ///\n'
    printf '    /// Plugins that need custom view providers should be registered\n'
    printf '    /// separately with `PluginAdapter<XxxPlugin>(...viewProvider:...)`.\n'
    printf '    ///\n'
    printf '    /// - Parameter register: Closure that handles the actual registration.\n'
    printf '    static func registerDefaultAdapters(_ register: (any SuperPlugin) -> Void) {\n'
    printf '%s\n' "$registry_entries" |
    while IFS='|' read -r struct_name package_name; do
        [ -n "$struct_name" ] || continue
        printf '        if %s.shouldRegister { register(PluginAdapter<%s>()) }\n' "$struct_name" "$struct_name"
    done
    printf '    }\n'
    printf '}\n'
} > "$TMP_OUTPUT"

if [ -f "$OUTPUT" ] && cmp -s "$TMP_OUTPUT" "$OUTPUT"; then
    rm "$TMP_OUTPUT"
else
    mv "$TMP_OUTPUT" "$OUTPUT"
fi
