#!/bin/sh
set -eu

# ==============================================================================
# generate_plugin_registry.sh
#
# Scans plugin packages for enabled types conforming to GitOKPlugin and
# generates Packages/GitOKPluginRegistry.
#
# Inspired by Cisum's Scripts/generate_plugin_registry.sh.
# ==============================================================================

ROOT_DIR="${SRCROOT:-$(cd "$(dirname "$0")/.." && pwd)}"
PLUGINS_DIR="$ROOT_DIR/Plugins"
REGISTRY_PACKAGE_DIR="$ROOT_DIR/Packages/GitOKPluginRegistry"
OUTPUT="$REGISTRY_PACKAGE_DIR/Sources/GitOKPluginRegistry/GeneratedPluginRegistry.swift"
TMP_OUTPUT="$OUTPUT.tmp"
MANIFEST="$REGISTRY_PACKAGE_DIR/Package.swift"
TMP_MANIFEST="$MANIFEST.tmp"

# ---------------------------------------------------------------------------
# 1. Scan for GitOKPlugin conformances
#    Pattern: public struct <Name>Plugin: GitOKPlugin {
# ---------------------------------------------------------------------------

registry_entries=$(
    find "$PLUGINS_DIR" -mindepth 4 -maxdepth 4 -path "$PLUGINS_DIR/Plugin*/Sources/*/*.swift" -print |
    sort |
    while IFS= read -r plugin_file; do
        struct_name=$(sed -n 's/^[[:space:]]*public struct \([A-Za-z0-9_]*Plugin\):.*GitOKPlugin.*/\1/p' "$plugin_file" | head -1)
        [ -n "$struct_name" ] || continue

        if ! grep -Eq 'policy:[[:space:]]*\.(alwaysOn|optOut|optIn)' "$plugin_file"; then
            continue
        fi

        package_name=$(printf '%s\n' "$plugin_file" | sed "s#^$PLUGINS_DIR/##; s#/.*##")
        [ -n "$package_name" ] || continue

        printf '%s|%s\n' "$struct_name" "$package_name"
    done
)

registry_entries=$(printf '%s\n' "$registry_entries" | awk 'NF > 0' | sort -u)
registry_imports=$(printf '%s\n' "$registry_entries" | awk -F'|' '{ print $2 }' | sort -u)

if [ -z "$registry_entries" ]; then
    # No active plugins — generate an empty registry stub instead of deleting
    # the package so the Xcode project reference remains valid.
    mkdir -p "$REGISTRY_PACKAGE_DIR"
    mkdir -p "$(dirname "$OUTPUT")"
    {
        printf 'import GitOKCoreKit\n\n'
        printf '/// Auto-generated plugin registry.\n'
        printf '/// No active plugins found (all use `.disabled` policy).\n'
        printf 'public enum GeneratedPluginRegistry {\n'
        printf '    public static let hasDefaultAdapters = false\n\n'
        printf '    @MainActor\n'
        printf '    public static func registerDefaultAdapters(\n'
        printf '        adapterFactory: any GitOKPluginAdapterFactory,\n'
        printf '        _ register: (any SuperPlugin) -> Void\n'
        printf '    ) {\n'
        printf '    }\n'
        printf '}\n'
    } > "$TMP_OUTPUT"
    if [ -f "$OUTPUT" ] && cmp -s "$TMP_OUTPUT" "$OUTPUT"; then
        rm "$TMP_OUTPUT"
    else
        mv "$TMP_OUTPUT" "$OUTPUT"
    fi
    exit 0
fi

# ---------------------------------------------------------------------------
# 2. Generate the Swift package manifest
# ---------------------------------------------------------------------------

mkdir -p "$REGISTRY_PACKAGE_DIR"
mkdir -p "$(dirname "$OUTPUT")"

{
    printf '// swift-tools-version: 6.0\n'
    printf 'import PackageDescription\n\n'
    printf 'let package = Package(\n'
    printf '    name: "GitOKPluginRegistry",\n'
    printf '    platforms: [\n'
    printf '        .macOS(.v15),\n'
    printf '    ],\n'
    printf '    products: [\n'
    printf '        .library(\n'
    printf '            name: "GitOKPluginRegistry",\n'
    printf '            targets: ["GitOKPluginRegistry"]\n'
    printf '        ),\n'
    printf '    ],\n'
    printf '    dependencies: [\n'
    printf '        .package(path: "../GitOKCoreKit"),\n'
    printf '%s\n' "$registry_imports" |
    while IFS= read -r package_name; do
        [ -n "$package_name" ] || continue
        printf '        .package(path: "../../Plugins/%s"),\n' "$package_name"
    done
    printf '    ],\n'
    printf '    targets: [\n'
    printf '        .target(\n'
    printf '            name: "GitOKPluginRegistry",\n'
    printf '            dependencies: [\n'
    printf '                "GitOKCoreKit",\n'
    printf '%s\n' "$registry_imports" |
    while IFS= read -r package_name; do
        [ -n "$package_name" ] || continue
        printf '                "%s",\n' "$package_name"
    done
    printf '            ],\n'
    printf '            path: "Sources/GitOKPluginRegistry"\n'
    printf '        ),\n'
    printf '    ]\n'
    printf ')\n'
} > "$TMP_MANIFEST"

if [ -f "$MANIFEST" ] && cmp -s "$TMP_MANIFEST" "$MANIFEST"; then
    rm "$TMP_MANIFEST"
else
    mv "$TMP_MANIFEST" "$MANIFEST"
fi

# ---------------------------------------------------------------------------
# 3. Generate the Swift file
# ---------------------------------------------------------------------------

{
    printf '// This file is generated by Scripts/generate_plugin_registry.sh.\n'
    printf '// Do not edit by hand.\n\n'
    printf 'import GitOKCoreKit\n'
    printf '%s\n' "$registry_imports" |
    while IFS= read -r package_name; do
        [ -n "$package_name" ] || continue
        printf 'import %s\n' "$package_name"
    done
    printf '\n'
    printf '/// Auto-generated plugin registry.\n'
    printf '/// Registers plugin adapters generated from enabled plugin packages.\n'
    printf 'public enum GeneratedPluginRegistry {\n'
    if [ -n "$registry_entries" ]; then
        printf '    public static let hasDefaultAdapters = true\n\n'
    else
        printf '    public static let hasDefaultAdapters = false\n\n'
    fi
    printf '    /// Register default plugin adapters for all enabled plugin packages.\n'
    printf '    ///\n'
    printf '    /// - Parameters:\n'
    printf '    ///   - adapterFactory: Factory supplied by the host app to preserve app-specific bridging.\n'
    printf '    ///   - register: Closure that handles the actual registration.\n'
    printf '    @MainActor\n'
    printf '    public static func registerDefaultAdapters(\n'
    printf '        adapterFactory: any GitOKPluginAdapterFactory,\n'
    printf '        _ register: (any SuperPlugin) -> Void\n'
    printf '    ) {\n'
    printf '%s\n' "$registry_entries" |
    while IFS='|' read -r struct_name package_name; do
        [ -n "$struct_name" ] || continue
        printf '        if %s.shouldRegister { register(adapterFactory.makeAdapter(for: %s.shared)) }\n' "$struct_name" "$struct_name"
    done
    printf '    }\n'
    printf '}\n'
} > "$TMP_OUTPUT"

if [ -f "$OUTPUT" ] && cmp -s "$TMP_OUTPUT" "$OUTPUT"; then
    rm "$TMP_OUTPUT"
else
    mv "$TMP_OUTPUT" "$OUTPUT"
fi
