#!/bin/sh
set -eu

# ==============================================================================
# generate_plugin_registry.sh
#
# Scans Plugins/Plugin* for types conforming to GitOKPackagedPlugin and
# generates APP/Core/Generated/GeneratedPluginRegistry.swift.
#
# Inspired by Cisum's Scripts/generate_plugin_registry.sh.
# ==============================================================================

ROOT_DIR="${SRCROOT:-$(cd "$(dirname "$0")/.." && pwd)}"
PLUGINS_DIR="$ROOT_DIR/Plugins"
OUTPUT="$ROOT_DIR/APP/Generated/GeneratedPluginRegistry.swift"
TMP_OUTPUT="$OUTPUT.tmp"

mkdir -p "$(dirname "$OUTPUT")"

# ---------------------------------------------------------------------------
# 1. Scan for GitOKPackagedPlugin conformances
#    Pattern: public struct <Name>Plugin: GitOKPackagedPlugin {
# ---------------------------------------------------------------------------

registry_entries=$(
    find "$PLUGINS_DIR" -mindepth 4 -maxdepth 4 -path "$PLUGINS_DIR/Plugin*/Sources/*/*.swift" -print |
    sort |
    while IFS= read -r plugin_file; do
        struct_name=$(sed -n 's/^[[:space:]]*public struct \([A-Za-z0-9_]*Plugin\):.*GitOKPackagedPlugin.*/\1/p' "$plugin_file" | head -1)
        [ -n "$struct_name" ] || continue

        package_name=$(printf '%s\n' "$plugin_file" | sed "s#^$PLUGINS_DIR/##; s#/.*##")
        [ -n "$package_name" ] || continue

        printf '%s|%s\n' "$struct_name" "$package_name"
    done
)

registry_entries=$(printf '%s\n' "$registry_entries" | awk 'NF > 0' | sort -u)
registry_imports=$(printf '%s\n' "$registry_entries" | awk -F'|' '{ print $2 }' | sort -u)

# ---------------------------------------------------------------------------
# 2. Generate the Swift file
# ---------------------------------------------------------------------------

{
    printf '// This file is generated by Scripts/generate_plugin_registry.sh.\n'
    printf '// Do not edit by hand.\n\n'
    printf 'import GitOKCoreKit\n'
    printf '%s\n' "$registry_imports" |
    while IFS= read -r package_name; do
        [ -n "$package_name" ] || continue
        printf 'import %s\n' "$package_name"
    done
    printf '\n'
    printf '/// Auto-generated plugin registry.\n'
    printf '/// Lists every `GitOKPackagedPlugin` found in Plugins/Plugin*.\n'
    printf 'enum GeneratedPluginRegistry {\n'
    printf '    /// All discovered packaged-plugin instances.\n'
    printf '    static var plugins: [any GitOKPackagedPlugin] {\n'
    printf '        var plugins: [any GitOKPackagedPlugin] = []\n'
    printf '%s\n' "$registry_entries" |
    while IFS='|' read -r struct_name package_name; do
        [ -n "$struct_name" ] || continue
        printf '        plugins.append(%s.shared)\n' "$struct_name"
    done
    printf '        return plugins\n'
    printf '    }\n'
    printf '\n'
    printf '    /// Register default `PackagedPluginAdapter` instances for all plugins.\n'
    printf '    /// Each adapter preserves the concrete generic type so that\n'
    printf '    /// `shouldRegister` / `order` etc. are resolved at compile time.\n'
    printf '    ///\n'
    printf '    /// Plugins that need custom view providers should be registered\n'
    printf '    /// separately with `PackagedPluginAdapter<XxxPlugin>(...viewProvider:...)`.\n'
    printf '    ///\n'
    printf '    /// - Parameter register: Closure that handles the actual registration.\n'
    printf '    static func registerDefaultAdapters(_ register: (any SuperPlugin) -> Void) {\n'
    printf '%s\n' "$registry_entries" |
    while IFS='|' read -r struct_name package_name; do
        [ -n "$struct_name" ] || continue
        # Use a simple index-like variable to avoid casing issues
        printf '        do { let a = PackagedPluginAdapter<%s>(); if type(of: a).shouldRegister { register(a) } }\n' "$struct_name"
    done
    printf '    }\n'
    printf '}\n'
} > "$TMP_OUTPUT"

if [ -f "$OUTPUT" ] && cmp -s "$TMP_OUTPUT" "$OUTPUT"; then
    rm "$TMP_OUTPUT"
else
    mv "$TMP_OUTPUT" "$OUTPUT"
fi
